### ISSUE TITLE
This site can't be reached—

### ISSUE THREAD

**Issue by mazal** [jeengbe/vality#118]
_(Sorry to intrude here—this repository is above my pay grade—but I often poke around GitHub to stretch my knowledge. I enjoyed a question/comment by @jeengbe made elsewhere regarding "deployments," accompanied by a fabulous graph, so I wanted to see his work, leading me here.)_ 

**The Issue:** Using Vivaldi (chromium flavor), on the first attempt at browsing to any ts-vality.io domain page, the result is an error message: "This site can’t be reached. Check if there is a typo in ts-vality.io." 

I attempted Firefox, Safari, and Chrome, also incognito. I don't use a proxy/firewall. I emptied the cache and temporarily turned on all permissions on at least one browser. I could not, under any of these circumstances, reach your website. I'm in the U.S. on MacOS. The Vality repo seems currently active, so I'm dropping a line.

<img width="300" alt="Screenshot 2024-01-29 at 8 32 32 AM" src="https://github.com/jeengbe/vality/assets/2043333/9ef74d03-6566-4c4a-aeef-fbea8f86a934">

**Comment by jeengbe** [comment]
Thanks a lot for reaching out!

I let the domain expire a while ago (I didn't deem it worth it, it got next to no visits), and I didn't get to updating the README. I had plans to update the documentation and port it to either GH Pages or pure Markdown. Either way — I forgot about it.

I'll try to find some time asap! 🙂

**Comment by mazal** [comment]
Thank you for the reply! It was a good exercise for me to formulate an "issue." I find GitHub so intimidating, so I appreciate the lightning-quick response. Good luck with the project. 🎉

**Comment by jeengbe** [comment]
You did great, thanks again for letting me know! 🙂
