### ISSUE TITLE
Relation Type

### ISSUE THREAD

**Issue by KevinGregull** [jeengbe/vality#13]
The relational type's TS signature is not compatible with its validator.
Currently is string (though configurable), but validation is always int number>0.

https://github.com/jeengbe/vality/blob/2ce9c634fc2196521b6dab89e327a70175a9d619/src/lib/guards.ts#L58

this should also be globally configureable. Also relation is a type that could specifically be null, if optional.

**Comment by jeengbe** [comment]
That's all up to you to configure.

You can overwrite Vality's built-in relation type by adding a property to the global configuration object as follows:
```ts
declare global {
  namespace vality {
    interface Config {
      // In this environment, a relation is referred to by a string
      RelationType: string;
    }
  }
}
```

This can then be implemented by simply overwriting `vality.relation`:
```ts
import { compose } from "vality/utils";

vality.relation = () =>
  guard(
    "relation",
    compose(
      vality.string
    )
  );
```

Just remember put these two in the same file and always include it.
