### ISSUE TITLE
Virtual/ReadOnly Type

### ISSUE THREAD

**Issue by KevinGregull** [jeengbe/vality#14]
Add a type that is included in Parse and therefore possibly part of the api's output, but not included in ParseIn, so we can have types that are visible in TS but are not validated succesfully. In case we have some types that are being set on the api. E.g. createdAt, createdBy, permissions..

**Comment by jeengbe** [comment]
Good suggestion, thank you

**Comment by jeengbe** [comment]
Yeah I forgot to actually implement this
